title: Pholio
author: GitHub User
email: info@pholio.io
description: > # this means to ignore newlines until "baseurl:"
  This is pholio site description, let make it longer

twitter_username: pholio_twitter
github_username:  pholio

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - package-lock.json
  - node_modules

plugins:
  - jekyll-seo-tag
